// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsnj3Vt5xnvRAcCJtDC-TjTD4vagC63WA',
    appId: '1:40543561438:web:4b7455b2c18df3a78ec44f',
    messagingSenderId: '40543561438',
    projectId: 'it-da-e4a42',
    authDomain: 'it-da-e4a42.firebaseapp.com',
    storageBucket: 'it-da-e4a42.appspot.com',
    measurementId: 'G-LTRTWFR5PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJQ-hlRDh40Ia2Z-V6d27JrAZbeIcXmC8',
    appId: '1:40543561438:android:09e874d68ade41658ec44f',
    messagingSenderId: '40543561438',
    projectId: 'it-da-e4a42',
    storageBucket: 'it-da-e4a42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB3NSi2vFR_ISQkZU-R3Y7Y1o1gewxIhU',
    appId: '1:40543561438:ios:01688e7105ba09d08ec44f',
    messagingSenderId: '40543561438',
    projectId: 'it-da-e4a42',
    storageBucket: 'it-da-e4a42.appspot.com',
    iosBundleId: 'com.example.itDa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB3NSi2vFR_ISQkZU-R3Y7Y1o1gewxIhU',
    appId: '1:40543561438:ios:ad42b85547d6de778ec44f',
    messagingSenderId: '40543561438',
    projectId: 'it-da-e4a42',
    storageBucket: 'it-da-e4a42.appspot.com',
    iosBundleId: 'com.example.itDa.RunnerTests',
  );
}
